# Generated by Django 5.0.3 on 2024-03-04 22:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(
                db_index=True,
                default=uuid.UUID("ff969265-17d9-4224-b3b8-48509196ffd8"),
                editable=False,
                unique=True,
                verbose_name="UUID",
            ),
        ),
    ]
